Entry.create! title: "Title1", body: "Message1"
Entry.create! title: "Title2", body: "Message2"
Entry.create! title: "Title3", body: "Message3"
Entry.create! title: "Title4", body: "Message4"
Entry.create! title: "Title5", body: "Message5"